# importing our dirty data to our code

In [1]:
import pandas as pd 
import numpy as np

In [3]:
Flood_Data_V0 = pd.read_csv("flood_risk_dataset_india.csv")
Flood_Data_V0

,Latitude,Longitude,Rainfall (mm),Temperature (°C),Humidity (%),River Discharge (m³/s),Water Level (m),Elevation (m),Land Cover,Soil Type,Population Density,Infrastructure,Historical Floods,Flood Occurred
0,18.861663,78.835584,218.999493,34.144337,43.912963,4236.182888,7.415552,377.465433,Water Body,Clay,7276.742184,1,0,1
1,35.570715,77.654451,55.353599,28.778774,27.585422,2472.585219,8.811019,7330.608875,Forest,Peat,6897.736956,0,1,0
2,29.227824,73.108463,103.991908,43.934956,30.108738,977.328053,4.631799,2205.873488,Agricultural,Loam,4361.518494,1,1,1
3,25.361096,85.610733,198.984191,21.569354,34.453690,3683.208933,2.891787,2512.277800,Desert,Sandy,6163.069701,1,1,0
4,12.524541,81.822101,144.626803,32.635692,36.292267,2093.390678,3.188466,2001.818223,Agricultural,Loam,6167.964591,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,32.872024,93.434120,285.682635,37.621017,69.795616,4830.703665,5.943965,2850.197900,Agricultural,Clay,6943.559433,0,0,0
9996,34.027756,69.357605,224.347263,37.935808,38.095486,1866.199787,9.466158,3314.692947,Forest,Clay,3011.997459,1,0,0
9997,35.454530,76.807256,5.836759,23.087083,79.919607,1523.374305,9.209185,3377.296962,Desert,Clay,7149.938303,1,0,1
9998,19.527152,80.856280,120.301453,28.029593,61.680873,2036.812638,2.004644,1146.986151,Water Body,Sandy,906.031452,1,0,1
9999,14.297072,72.995680,77.219394,29.622711,88.936537,2614.166967,0.991856,8381.595028,Desert,Clay,4530.770301,1,1,1

# The function for getting the range of each csv column data in Numerical range and Categorical values

In [5]:
# The function for getting the range of each csv column data in Numerical range and Categorical values  
def get_data_ranges(file_path):
    """
    Reads a CSV file and prints the range (min and max) of data for each column.
    
    Args:
        file_path (str): The path to the CSV file.
    """
    try:
        df = pd.read_csv(file_path)
        
        for column in df.columns:
            # For numerical data, calculate min and max
            if pd.api.types.is_numeric_dtype(df[column]):
                min_val = df[column].min()
                max_val = df[column].max()
                print(f"Column '{column}': Numerical Range [{min_val}, {max_val}]")
            
            # For categorical or string data, show unique values
            else:
                unique_values = df[column].unique()
                print(f"Column '{column}': Categorical/String Values {unique_values}")
                
    except FileNotFoundError:
        print(f"Error: The file at '{file_path}' was not found.")
    except Exception as e:
        print(f"An error occurred: {e}")

In [6]:
get_data_ranges('flood_risk_dataset_india.csv')

Column 'Latitude': Numerical Range [8.000337407905619, 36.99181252529779]
Column 'Longitude': Numerical Range [68.00457459276365, 96.99781997816213]
Column 'Rainfall (mm)': Numerical Range [0.014437168293524, 299.9702931027695]
Column 'Temperature (°C)': Numerical Range [15.00016610027214, 44.99368115437786]
Column 'Humidity (%)': Numerical Range [20.001338900634774, 99.9977717894386]
Column 'River Discharge (m³/s)': Numerical Range [0.0421610565215502, 4999.698480228592]
Column 'Water Level (m)': Numerical Range [0.0027012235672785, 9.996898773860396]
Column 'Elevation (m)': Numerical Range [1.1503397240072708, 8846.894877202165]
Column 'Land Cover': Categorical/String Values ['Water Body' 'Forest' 'Agricultural' 'Desert' 'Urban']
Column 'Soil Type': Categorical/String Values ['Clay' 'Peat' 'Loam' 'Sandy' 'Silt']
Column 'Population Density': Numerical Range [2.2890002655517883, 9999.169529703417]
Column 'Infrastructure': Numerical Range [0, 1]
Column 'Historical Floods': Numerical Range [0, 1]
Column 'Flood Occurred': Numerical Range [0, 1]

# create a map for converting string to int

# Land Cover ['Water Body' 'Forest' 'Agricultural' 'Desert' 'Urban']
# Land Cover ['1' '2' '3' '4' '5']
# Column 'Soil Type':  ['Clay' 'Peat' 'Loam' 'Sandy' 'Silt']
# Column 'Soil Type':  ['1' '2' '3' '4' '5']

In [8]:
import pandas as pd

# Define the mapping dictionaries for the columns
land_cover_map = {
    'Water Body': 1,
    'Forest': 2,
    'Agricultural': 3,
    'Desert': 4,
    'Urban': 5
}

soil_type_map = {
    'Clay': 1,
    'Peat': 2,
    'Loam': 3,
    'Sandy': 4,
    'Silt': 5
}

# Load your dataset
# Replace 'your_dataset.csv' with the name of your file
try:
    df = pd.read_csv('flood_risk_dataset_india.csv')
    
    # Check if the columns exist before mapping
    if 'Land Cover' in df.columns and 'Soil Type' in df.columns:
        # Apply the mappings to the specified columns
        df['Land Cover'] = df['Land Cover'].map(land_cover_map)
        df['Soil Type'] = df['Soil Type'].map(soil_type_map)
        
        # Save the new DataFrame to a new CSV file
        df.to_csv('mapped_dataset.csv', index=False)
        print("Columns successfully mapped and saved to 'mapped_dataset.csv'.")
    else:
        print("Error: The 'Land Cover' or 'Soil Type' columns were not found in the dataset.")
        
except FileNotFoundError:
    print("Error: 'your_dataset.csv' was not found. Please make sure the file is in the same directory as your script.")
except Exception as e:
    print(f"An error occurred: {e}")

Columns successfully mapped and saved to 'mapped_dataset.csv'.